# Generated by Django 4.0.3 on 2022-05-22 16:35

from django.db import migrations, models
import resources.models
import resources.types
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDependencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, null=True)),
                ('state_decision', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-created', 'id'],
                'get_latest_by': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='123456789abcdefghijklmnopqrstuvwxyz', editable=False, length=16, max_length=16, prefix='', primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=47, validators=[resources.models.validate_slug])),
                ('hcl_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('rtype', models.CharField(max_length=255, validators=[resources.models.validate_rtype])),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('creation_response', models.JSONField(blank=True, null=True)),
                ('list_response', models.JSONField(blank=True, null=True)),
                ('getter_response', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('desired_state', models.CharField(blank=True, choices=[('healthy', 'healthy'), ('deleted', 'deleted'), ('updated', 'updated'), ('untracked', 'untracked')], max_length=64, null=True)),
                ('state', models.CharField(choices=[('newborn_model', 'newborn_model'), ('dependencies_pending', 'dependencies_pending'), ('declared', 'declared'), ('exists', 'exists'), ('doesnt_exist', 'doesnt_exist'), ('healthy', 'healthy'), ('deleted', 'deleted'), ('unknown', 'unknown'), ('creation_terminated', 'creation_terminated')], default=resources.types.ResourceStateEnum['newborn_model'], max_length=64)),
                ('existence', models.CharField(choices=[('exists', 'exists'), ('doesnt_exist', 'doesnt_exist'), ('unknown', 'unknown')], default=resources.types.ExistenceEnum['unknown'], max_length=64)),
                ('existence_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('resource_created_at', models.DateTimeField(blank=True, null=True)),
                ('health', models.CharField(choices=[('healthy', 'healthy'), ('unhealthy', 'unhealthy'), ('unknown', 'unknown')], default=resources.types.HealthEnum['unknown'], max_length=64)),
                ('health_last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
