# Generated by Django 4.0.3 on 2022-05-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
        ('transitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.projectmodel'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='state_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourceeventmodel'),
        ),
        migrations.AddField(
            model_name='resourceeventmodel',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcemodel'),
        ),
        migrations.AddField(
            model_name='resourceeventmodel',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitions.transitionmodel'),
        ),
        migrations.AddField(
            model_name='resourcedependencymodel',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backward_rels', to='resources.resourcemodel'),
        ),
        migrations.AddField(
            model_name='resourcedependencymodel',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_rels', to='resources.resourcemodel'),
        ),
        migrations.AddConstraint(
            model_name='resourcemodel',
            constraint=models.UniqueConstraint(fields=('slug', 'rtype', 'project'), name='rtype_slug_is_unique_per_project'),
        ),
        migrations.AddConstraint(
            model_name='resourcemodel',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('hcl_slug', None), ('hcl_slug', ''), _connector='OR'), _negated=True), fields=('hcl_slug', 'project'), name='hcl_slug_is_unique_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcedependencymodel',
            unique_together={('resource', 'depends_on', 'field_name')},
        ),
    ]
