# Generated by Django 4.0.3 on 2022-05-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status_decision', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_info', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-created', 'id'],
                'get_latest_by': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ensure_dependencies_ready', 'ensure_dependencies_ready'), ('ensure_exists', 'ensure_exists'), ('ensure_healthy', 'ensure_healthy'), ('ensure_forward_dependencies_deleted', 'ensure_forward_dependencies_deleted'), ('ensure_deleted', 'ensure_deleted'), ('ensure_updated', 'ensure_updated'), ('test', 'test')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent_to_broker', 'sent_to_broker'), ('in_progress', 'in_progress'), ('succeeded', 'succeeded'), ('failed', 'failed')], max_length=64)),
                ('update_type', models.CharField(blank=True, max_length=64, null=True)),
                ('extra_task_kwargs', models.JSONField(blank=True, null=True)),
                ('celery_tasks', models.ManyToManyField(blank=True, to='django_celery_results.taskresult')),
                ('previous_transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitions.transitionmodel')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcemodel')),
                ('status_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transitions.transitioneventmodel')),
            ],
            options={
                'ordering': ['-created', 'id'],
                'get_latest_by': ['created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transitioneventmodel',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transitions.transitionmodel'),
        ),
    ]
